export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const LOADING = "LOADING";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
export const AUTH_NOTIFICATION = "AUTH_NOTIFICATION";

export const SUBMIT_VENUE_FORM_REQUEST = 'SUBMIT_VENUE_FORM_REQUEST';
export const SUBMIT_VENUE_FORM_SUCCESS = 'SUBMIT_VENUE_FORM_SUCCESS';
export const SUBMIT_VENUE_FORM_FAILURE = 'SUBMIT_VENUE_FORM_FAILURE';

export const GET_VENUES_REQUEST = 'GET_VENUES_REQUEST'
export const GET_VENUES_SUCCESS = 'GET_VENUES_SUCCESS'
export const GET_VENUES_FAILURE = 'GET_VENUES_FAILURE'

export const DELETE_VENUE_REQUEST = 'DELETE_VENUE_REQUEST'
export const DELETE_VENUE_SUCCESS = 'DELETE_VENUE_SUCCESS'
export const DELETE_VENUE_FAILURE = 'DELETE_VENUE_FAILURE'