export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const LOADING = "LOADING";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
export const AUTH_NOTIFICATION = "AUTH_NOTIFICATION";

export const SUBMIT_VENUE_FORM_REQUEST = 'SUBMIT_VENUE_FORM_REQUEST';
export const SUBMIT_VENUE_FORM_SUCCESS = 'SUBMIT_VENUE_FORM_SUCCESS';
export const SUBMIT_VENUE_FORM_FAILURE = 'SUBMIT_VENUE_FORM_FAILURE';

export const GET_VENUES_REQUEST = 'GET_VENUES_REQUEST'
export const GET_VENUES_SUCCESS = 'GET_VENUES_SUCCESS'
export const GET_VENUES_FAILURE = 'GET_VENUES_FAILURE'

export const GET_SINGLE_VENUE_REQUEST = 'GET_SINGLE_VENUE_REQUEST'
export const GET_SINGLE_VENUE_SUCCESS = 'GET_SINGLE_VENUE_SUCCESS'
export const GET_SINGLE_VENUE_FAILURE = 'GET_SINGLE_VENUE_FAILURE'

export const DELETE_VENUE_REQUEST = 'DELETE_VENUE_REQUEST'
export const DELETE_VENUE_SUCCESS = 'DELETE_VENUE_SUCCESS'
export const DELETE_VENUE_FAILURE = 'DELETE_VENUE_FAILURE'

export const SUBMIT_VENDOR_FORM_REQUEST = 'SUBMIT_VENDOR_FORM_REQUEST';
export const SUBMIT_VENDOR_FORM_SUCCESS = 'SUBMIT_VENDOR_FORM_SUCCESS';
export const SUBMIT_VENDOR_FORM_FAILURE = 'SUBMIT_VENDOR_FORM_FAILURE';

export const GET_VENDORS_REQUEST = 'GET_VENDORS_REQUEST'
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS'
export const GET_VENDORS_FAILURE = 'GET_VENDORS_FAILURE'

export const DELETE_VENDOR_REQUEST = 'DELETE_VENDOR_REQUEST'
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS'
export const DELETE_VENDOR_FAILURE = 'DELETE_VENDOR_FAILURE'

export const PAYMENT_INTENT_SUCCESS = 'PAYMENT_INTENT_SUCCESS';
export const PAYMENT_INTENT_FAILURE = 'PAYMENT_INTENT_FAILURE';
export const PAYMENT_INTENT_REQUEST = 'PAYMENT_INTENT_REQUEST';

export const CHECK_AVAILABILITY_REQUEST = 'CHECK_AVAILABILITY_REQUEST';
export const CHECK_AVAILABILITY_SUCCESS = 'CHECK_AVAILABILITY_SUCCESS';
export const CHECK_AVAILABILITY_FAILURE = 'CHECK_AVAILABILITY_FAILURE';

export const SEND_BOOKING_REQUEST = 'SEND_BOOKING_REQUEST';
export const SEND_BOOKING_SUCCESS = 'SEND_BOOKING_SUCCESS';
export const SEND_BOOKING_FAILURE = 'SEND_BOOKING_FAILURE';

export const ACCEPT_BOOKING_REQUEST = 'ACCEPT_BOOKING_REQUEST';
export const ACCEPT_BOOKING_SUCCESS = 'ACCEPT_BOOKING_SUCCESS';
export const ACCEPT_BOOKING_FAILURE = 'ACCEPT_BOOKING_FAILURE';

export const REJECT_BOOKING_REQUEST = 'REJECT_BOOKING_REQUEST';
export const REJECT_BOOKING_SUCCESS = 'REJECT_BOOKING_SUCCESS';
export const REJECT_BOOKING_FAILURE = 'REJECT_BOOKING_FAILURE';

export const GET_BOOKINGS_FOR_PROVIDER_REQUEST = 'GET_BOOKINGS_FOR_PROVIDER_REQUEST';
export const GET_BOOKINGS_FOR_PROVIDER_SUCCESS = 'GET_BOOKINGS_FOR_PROVIDER_SUCCESS';
export const GET_BOOKINGS_FOR_PROVIDER_FAILURE = 'GET_BOOKINGS_FOR_PROVIDER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const PASSWORD_VERIFICATION_REQUEST = 'PASSWORD_VERIFICATION_REQUEST';
export const PASSWORD_VERIFICATION_SUCCESS = 'PASSWORD_VERIFICATION_SUCCESS';
export const PASSWORD_VERIFICATION_FAILURE = 'PASSWORD_VERIFICATION_FAILURE';

export const ADD_PAYMENT_METHOD_REQUEST = 'ADD_PAYMENT_METHOD_REQUEST';
export const ADD_PAYMENT_METHOD_SUCCESS = 'ADD_PAYMENT_METHOD_SUCCESS';
export const ADD_PAYMENT_METHOD_FAILURE = 'ADD_PAYMENT_METHOD_FAILURE';

export const GET_PAYMENT_METHOD_REQUEST = 'GET_PAYMENT_METHOD_REQUEST';
export const GET_PAYMENT_METHOD_SUCCESS = 'GET_PAYMENT_METHOD_SUCCESS';
export const GET_PAYMENT_METHOD_FAILURE = 'GET_PAYMENT_METHOD_FAILURE';

export const UPDATE_PAYMENT_METHOD_REQUEST = 'UPDATE_PAYMENT_METHOD_REQUEST';
export const UPDATE_PAYMENT_METHOD_SUCCESS = 'UPDATE_PAYMENT_METHOD_SUCCESS';
export const UPDATE_PAYMENT_METHOD_FAILURE = 'UPDATE_PAYMENT_METHOD_FAILURE';

export const DELETE_PAYMENT_METHOD_REQUEST = 'DELETE_PAYMENT_METHOD_REQUEST';
export const DELETE_PAYMENT_METHOD_SUCCESS = 'DELETE_PAYMENT_METHOD_SUCCESS';
export const DELETE_PAYMENT_METHOD_FAILURE = 'DELETE_PAYMENT_METHOD_FAILURE';

export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const MARK_AS_READ = 'MARK_AS_READ';
export const MARK_ALL_AS_READ = 'MARK_ALL_AS_READ';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';

export const ADD_STAFF_REQUEST = 'ADD_STAFF_REQUEST';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAILURE = 'ADD_STAFF_FAILURE';

export const GET_STAFF_REQUEST = 'GET_STAFF_REQUEST';
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS';
export const GET_STAFF_FAILURE = 'GET_STAFF_FAILURE';

export const GET_ALL_STAFF_REQUEST = 'GET_ALL_STAFF_REQUEST';
export const GET_ALL_STAFF_SUCCESS = 'GET_ALL_STAFF_SUCCESS';
export const GET_ALL_STAFF_FAILURE = 'GET_ALL_STAFF_FAILURE';

export const EDIT_STAFF_REQUEST = 'EDIT_STAFF_REQUEST';
export const EDIT_STAFF_SUCCESS = 'EDIT_STAFF_SUCCESS';
export const EDIT_STAFF_FAILURE = 'EDIT_STAFF_FAILURE';

export const DELETE_STAFF_REQUEST = 'DELETE_STAFF_REQUEST';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAILURE = 'DELETE_STAFF_FAILURE';

export const CUSTOMER_HIRE_STAFF_REQUEST = 'CUSTOMER_HIRE_STAFF_REQUEST';
export const CUSTOMER_HIRE_STAFF_SUCCESS = 'CUSTOMER_HIRE_STAFF_SUCCESS';
export const CUSTOMER_HIRE_STAFF_FAILURE = 'CUSTOMER_HIRE_STAFF_FAILURE';

export const VENUE_PROVIDER_HIRE_STAFF_REQUEST = 'VENUE_PROVIDER_HIRE_STAFF_REQUEST';
export const VENUE_PROVIDER_HIRE_STAFF_SUCCESS = 'VENUE_PROVIDER_HIRE_STAFF_SUCCESS';
export const VENUE_PROVIDER_HIRE_STAFF_FAILURE = 'VENUE_PROVIDER_HIRE_STAFF_FAILURE';

export const CHECK_STAFF_AVAILABILITY_REQUEST = 'CHECK_STAFF_AVAILABILITY_REQUEST';
export const CHECK_STAFF_AVAILABILITY_SUCCESS = 'CHECK_STAFF_AVAILABILITY_SUCCESS';
export const CHECK_STAFF_AVAILABILITY_FAILURE = 'CHECK_STAFF_AVAILABILITY_FAILURE';

export const ACCEPT_HIRE_REQUEST_REQUEST = 'ACCEPT_HIRE_REQUEST_REQUEST';
export const ACCEPT_HIRE_REQUEST_SUCCESS = 'ACCEPT_HIRE_REQUEST_SUCCESS';
export const ACCEPT_HIRE_REQUEST_FAILURE = 'ACCEPT_HIRE_REQUEST_FAILURE';

export const REJECT_HIRE_REQUEST_REQUEST = 'REJECT_HIRE_REQUEST_REQUEST';
export const REJECT_HIRE_REQUEST_SUCCESS = 'REJECT_HIRE_REQUEST_SUCCESS';
export const REJECT_HIRE_REQUEST_FAILURE = 'REJECT_HIRE_REQUEST_FAILURE';

export const GET_HIRE_REQUESTS_BY_HIRER_ID_REQUEST = 'GET_HIRE_REQUESTS_BY_HIRER_ID_REQUEST';
export const GET_HIRE_REQUESTS_BY_HIRER_ID_SUCCESS = 'GET_HIRE_REQUESTS_BY_HIRER_ID_SUCCESS';
export const GET_HIRE_REQUESTS_BY_HIRER_ID_FAILURE = 'GET_HIRE_REQUESTS_BY_HIRER_ID_FAILURE';

export const GET_HIRE_REQUESTS_FOR_USER_REQUEST = 'GET_HIRE_REQUESTS_FOR_USER_REQUEST';
export const GET_HIRE_REQUESTS_FOR_USER_SUCCESS = 'GET_HIRE_REQUESTS_FOR_USER_SUCCESS';
export const GET_HIRE_REQUESTS_FOR_USER_FAILURE = 'GET_HIRE_REQUESTS_FOR_USER_FAILURE';

export const GET_BOOKINGS_FOR_CUSTOMER_REQUEST = 'GET_BOOKINGS_FOR_CUSTOMER_REQUEST';
export const GET_BOOKINGS_FOR_CUSTOMER_SUCCESS = 'GET_BOOKINGS_FOR_CUSTOMER_SUCCESS';
export const GET_BOOKINGS_FOR_CUSTOMER_FAILURE = 'GET_BOOKINGS_FOR_CUSTOMER_FAILURE';

export const GET_VENUE_BY_USER_REQUEST = 'GET_VENUE_BY_USER_REQUEST'
export const GET_VENUE_BY_USER_SUCCESS = 'GET_VENUE_BY_USER_SUCCESS'
export const GET_VENUE_BY_USER_FAILURE = 'GET_VENUE_BY_USER_FAILURE'